version: '2'
services:
  java-api:
    image: maven
    volumes:
    - "./java-api:/deploy"
    working_dir: "/deploy"
    ports:
    - "8080:8080"
    command: bash -c "mvn clean && mvn install && java -jar target/offline-0.0.1.jar"
    container_name: JavaAPI